name: Lint

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run Multi-Linter
        uses: ./action
        with:
          config_file: config/linter-config.yaml
          fail_on_error: true
          report_format: github
